services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://revobank:revobank@db:5432/revobank
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=revobank
      - POSTGRES_PASSWORD=revobank
      - POSTGRES_DB=revobank
    ports:
      - "5432:5432"

volumes:
  postgres_data:
